### PR TITLE
RFC: Refactor the package to make it self-generated and more

### LINKED ISSUE #49: failure to build on OS X (v0.0.0 and master)
``` julia
julia> Pkg.build("Clang")
INFO: Building Clang
g++ wrapclang.cpp -fPIC -c -o wrapclang.cpp.o -I"/Users/stefan/projects/julia//usr/include" -g -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fPIC
wrapclang.cpp:6:10: fatal error: 'clang-c/Index.h' file not found
#include "clang-c/Index.h"
         ^
1 error generated.
make: *** [wrapclang.cpp.o] Error 1
================================[ ERROR: Clang ]================================

failed process: Process(`make`, ProcessExited(2)) [2]
while loading /Users/stefan/.julia/Clang/deps/build.jl, in expression starting on line 6

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Clang had build errors.

 - packages with build errors remain installed in /Users/stefan/.julia
 - build a package and all its dependencies with `Pkg.build(pkg)`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

Not sure where to start debugging this.

### LINKED ISSUE #65: Fails build with 'printf' was not declared in this scope
Updated after my comment in #5982 but still get

```
julia> Pkg.build("Clang")
INFO: Building Clang
g++ wrapclang.cpp -fPIC -c -o wrapclang.cpp.o -I/c/programs/julia64/deps/llvm-3.3/include -g -Wall -
Wno-strict-aliasing -fno-omit-frame-pointer -fPIC -IC:/programs/llvm_trunk/compileds/include
wrapclang.cpp:1:0: warning: -fPIC ignored for target (all code is position independent) [enabled by
default]
wrapclang.cpp: In function 'void wci_debug_token(CXTranslationUnit, char*)':
wrapclang.cpp:118:69: error: 'printf' was not declared in this scope
wrapclang.cpp: In function 'void wci_print_tokens(CXTranslationUnit, char*)':
wrapclang.cpp:131:71: error: 'printf' was not declared in this scope
make: *** [wrapclang.cpp.o] Error 1
```

### LINKED ISSUE #75: Failed to find libwrapclang
```
julia> using Clang
ERROR: assertion failed: Failed to find required library libwrapclang. Try re-running the package script using Pkg.build("Clang")
```

I tried rebuilding as suggested, with no success. I'm on OSX 10.8.5. I build `llvm` from Homebrew using `brew install llvm --with-clang` and in Julia I set

```
ENV["LLVM_CONFIG"] = "/usr/local/Cellar/llvm/3.4/bin/llvm-config"
```

The problem seems to come from line 2 of `ext.jl`:

```
const libwci = find_library(["libwrapclang",],[Pkg.dir("Clang", "deps", "usr", "lib"),])
```

Am I supposed to add `~/.julia/v0.3/Clang/deps/usr/lib` to my `LD_LIBRARY_PATH`? How do I do that so Julia is aware of it? Setting it in the shell doesn't resolve the issue.

Thanks.

### LINKED ISSUE #142: runtests.jl Segmentation fault- clang_getTranslationUnitCursor at /usr/bin/../lib/x86_64-linux-gnu/libclang-3.6.so.1
Hi all,
I am trying to deploy Clang for future development of julia interface for GRASS GIS.
After checkout master Clang build[2] works. If I run tests from Clang.jl I got errors[1]. I am not sure on what I should focus from this error message. Additional info of system [3] 

[1]

```
PC:~/.julia/v0.5/Clang/test$ julia runtests.jl 

signal (11): Segmentation fault
clang_getTranslationUnitCursor at /usr/bin/../lib/x86_64-linux-gnu/libclang-3.6.so.1 (unknown line)
wci_getTranslationUnitCursor at /home/matt/.julia/v0.5/Clang/src/../deps/usr/lib/libwrapclang.so (unknown line)
tu_cursor at /home/matt/.julia/v0.5/Clang/src/cindex.jl:349
parse_header at /home/matt/.julia/v0.5/Clang/src/cindex.jl:67
jlcall___parse_header#0___21984 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
julia_parse_header_21982 at  (unknown line)
unknown function (ip: 0x7f0fa84b7633)
unknown function (ip: 0x7f0fa84b6a71)
unknown function (ip: 0x7f0fa84b677d)
unknown function (ip: 0x7f0fa84b7c85)
unknown function (ip: 0x7f0fa84b8079)
unknown function (ip: 0x7f0fa84cbdaf)
unknown function (ip: 0x7f0fa84cc679)
jl_load at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
include at ./boot.jl:261
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
include_from_node1 at ./loading.jl:304
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 0x7f0fa84b7633)
unknown function (ip: 0x7f0fa84b6a71)
unknown function (ip: 0x7f0fa84cb988)
unknown function (ip: 0x7f0fa84cc679)
jl_load at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
include at ./boot.jl:261
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
include_from_node1 at ./loading.jl:304
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
process_options at ./client.jl:279
_start at ./client.jl:375
unknown function (ip: 0x7f0fa5023cf9)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 0x401b41)
unknown function (ip: 0x40171f)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x401765)
unknown function (ip: (nil))
Segmentation fault (core dumped)
```

[2]

```
julia> ENV["LLVM_CONFIG"]="/usr/lib/llvm-3.6/bin/llvm-config"
julia>Pkg.clone("https://github.com/ihnorton/Clang.jl.git")
...
julia> Pkg.build("Clang")
INFO: Building Clang
g++ wrapclang.cpp -fPIC -c -o wrapclang.cpp.o -I/usr/lib/llvm-3.6/include -g -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fPIC 
g++ wrapclang.cpp.o -rdynamic -shared -o libwrapclang.so -L/usr/lib/llvm-3.6/lib  -L/usr/lib/llvm-3.6/lib -lclang
```

[3]

```
Installed libs
matt@matt-pc:~/.julia/v0.5/Clang/test$ dpkg --get-selections | grep llvm
libllvm-3.6-ocaml-dev               install
libllvm3.4:amd64                install
libllvm3.4:i386                 deinstall
libllvm3.6:amd64                install
libllvm3.6-dbg:amd64                install
llvm-3.6                    install
llvm-3.6-dev                    install
llvm-3.6-doc                    install
llvm-3.6-examples               install
llvm-3.6-runtime                install

matt@matt-pc:~/.julia/v0.5/Clang/test$ dpkg --get-selections | grep libclang
libclang-3.4-dev                install
libclang-3.6-dev                install
libclang-common-3.4-dev             install
libclang-common-3.6-dev             install
libclang-dev                    install
libclang1-3.4:amd64             install
libclang1-3.6:amd64             install
libclang1-3.6-dbg               install


  | | |_| | | | (_| |  |  Version 0.5.0-dev+433 (2015-09-29 15:39 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit e60fd18 (15 days old master)
|__/                   |  x86_64-linux-gnu


```

Does anyone now how I should figure out problem? Thanks for any advice! 

best Matej

### LINKED ISSUE #145: Build error on OS X (`unrecognized command line option '-rdynamic'`)
I cannot build `Clang` on OS X El Capitan. I installed `g++` via Macports; this is gcc 5.2.

```
julia> Pkg.build("Clang")
INFO: Building Clang
g++ wrapclang.cpp.o -rdynamic -shared -o libwrapclang.dylib -L/opt/local/libexec/llvm-3.7/lib  -L/opt/local/libexec/llvm-3.7/lib -lclang
g++: error: unrecognized command line option '-rdynamic'
make: *** [libwrapclang.dylib] Error 1
================================[ ERROR: Clang ]================================

LoadError: failed process: Process(`make`, ProcessExited(2)) [2]
while loading /Users/eschnett/.julia/v0.4/Clang/deps/build.jl, in expression starting on line 19

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Clang had build errors.

 - packages with build errors remain installed in /Users/eschnett/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Clang")`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

### LINKED ISSUE #163: Feature (or documentation) request: a more generic, portable way of dealing with errors like "fatal error: 'stddef.h' file not found"
Trying to use Clang.jl on Arch Linux, clang 3.7.1-1, i'm getting the dreaded error mentioned above:

``` julia
julia> using Clang.cindex

julia> topcu = cindex.parse_header("/usr/include/stdio.h", args = ["-v"])
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /../lib/gcc/x86_64-unknown-linux-gnu/5.3.0
Found candidate GCC installation: /../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-unknown-linux-gnu/5.3.0
Selected GCC installation: /../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
ignoring nonexistent directory "../lib/clang/3.7.1/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/include
End of search list.
/usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found
CLCursor (Clang.cindex.TranslationUnit) /usr/include/stdio.h
```

Naturally I have read the FAQ entry on libclang tooling, so I know that I have to supply the correct path to Clang's built-in include files.

While looking at Clang's sources, in particular [this line](https://github.com/llvm-mirror/clang/blob/76ace1ff8d66981fcf542fb62e0539b203111479/test/lit.cfg#L220), I came up with the following: why not retrieve the correct include path automatically?

Reworking the example in `README.md`, I came up with

``` julia
julia> incpath = chomp(readall(`clang -print-file-name=include`))
"/usr/bin/../lib/clang/3.7.1/include"

julia> topcu = cindex.parse_header("/usr/include/stdio.h", args = ["-nobuiltininc", "-I$incpath"])
CLCursor (Clang.cindex.TranslationUnit) /usr/include/stdio.h

julia> cu = cindex.search(topcu, "printf")[1]
CLCursor (Clang.cindex.FunctionDecl) printf(const char *restrict, ...)
```

(Note: I added the `-nobuiltininc` flag to prevent the tool from picking up any stray header files stored in a `../lib/clang/...` directory which could happen to exist alongside the current directory.)
I was wondering if this could somehow be incorporated into this package's build process, or at least added to the documentation for use by wrapper creators.
This should make non-portable, highly platform/version specific hacks like [this](https://github.com/JuliaLang/Sundials.jl/blob/252337d9f434f1bb9491fa55dbce9df5e406076f/src/wrap_sundials.jl#L36-L40) unnecessary.

Any comments or suggestions are very welcome.

### LINKED ISSUE #172: Build Failure
Trying to build with julia 0.5 I got the following error:

```bash
jared@k475:~/.julia/v0.5/Clang/deps$ julia5 ./build.jl 
g++ wrapclang.cpp -fPIC -c -o wrapclang.cpp.o -I/home/jared/build/clang_3.7/include -g -I/home/jared/build/clang_3.7/include  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -O3 -DNDEBUG -fno-exceptions -fno-rtti  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fPIC 
g++: error: unrecognized command line option ‘-Wcovered-switch-default’
make: *** [wrapclang.cpp.o] Error 1
ERROR: LoadError: clang headers could not be found and BUILD_LLVM_CLANG=1 not specified in Make.user
Try setting BUILD_LLVM_CLANG=1 in Make.user in /mnt/external/build/julia_0.5/usr/bin and try again.
 in error(::String) at ./error.jl:21
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/jared/.julia/v0.5/Clang/deps/build.jl, in expression starting on line 59
```

I am using g++ 4.8.4

### LINKED ISSUE #183: Where should llvm-config be on windows?
I could not find llvm-config on windows. I downloaded many precompiled versions (4.0.1, 5.0.0, 3.4.0).
Any Ideas?

### LINKED ISSUE #190: wrap_c generating incorrect signature for typedef'ed pointers
This is an issue similar to #152. See this [discourse post](https://discourse.julialang.org/t/how-to-get-a-pointer-ptr-t-that-references-a-variable-of-type-t/9273/9?u=tk3369) for more details.

Example:
```c
typedef struct {
    double x;
} FOO, *FOOP;

FOOP test1(double a, double b, FOOP c);
```

got wrapped as:

```julia
function test1(a::Cdouble, b::Cdouble, c::FOOP)
    ccall((:test1, test), FOOP, (Cdouble, Cdouble, FOOP), a, b, c)
end
```

Expected result should be:
```julia
function test1(a::Cdouble, b::Cdouble, c)
    ccall((:test1, test), FOOP, (Cdouble, Cdouble, FOOP), a, b, c)
end
```

### LINKED ISSUE #197: could not open file .......\packages\Clang\vnNvW\deps\deps.jl
Tried to build it (on Win) but it errors with this. And actually there is no ``deps.jl`` in soure code.

```
julia> using Clang
[ Info: Precompiling Clang [40e3b903-d033-50b4-a0cc-940c62c95e31]
ERROR: LoadError: LoadError: could not open file C:\Users\j\.julia\packages\Clang\vnNvW\deps\deps.jl
```

### LINKED ISSUE #208: typedef anonymous structs should not be skipped
```c
typedef struct {
  int x;
} Foo;
```
output: `const Foo = Cvoid`

### LINKED ISSUE #211: Use BinaryProvider for All OSes
This would take a lot of the guess work out of making sure that LLVM is installed. It would also allow the libclang used to match julia's LLVM.

### PR DESCRIPTION
**Pull request by Gnimuc**
I'm investigating how to rebuild the package directly on the auto-generated libclang bindings. Almost done. Please give it a review at your convenience ;)

## Change Summary
* rebuild `Clang.jl` directly on top of the auto-generated libclang C bindings
  - the new submodule `LibClang` is one-to-one mapped to the libclang C APIs. it depends on two new files: `CEnum.jl` and `ctypes.jl`. `CEnum.jl` is for better C-compatible enum handling. `ctypes.jl` contains those C stdlib types that are missing corresponding Julia aliases. when generating wrappers, we should also ship these two files to users.
  - module `cindex`'s base functions are now rebuild on top of LibClang. almost all of the old APIs are renamed, please take a look at `index.jl`, `trans_unit.jl`, `cursor.jl`, `type.jl`, `token.jl` and `show.jl` for details.
  - ~~module `cindex`'s CL-prefixed types are removed, since methods are now directly dynamic-dispatched on `Val{CEnum}` value types(not sure whether this is a good idea or not).~~
  - unwind `wrap_c.jl` and add an AbstractContext type for extensibility
    + this is easier for users who would like to write their own `wrap!` for certain cursor decls
    and dispatched on their own context.
    + for compatibility's sake, `init`+`run` are rebuild on top of `DefaultContext`. also, old `cindex` and `wrap_c` modules can be loaded with `Clang.Deprecated.cindex; using Clang.Deprecated.wrap_c;`
* provide an out-of-box installation experience with BB2 on Linux, masOS and Windows, this may attract more users to use this package.
  - the newly released binaries of `LLVMBuilder` are still not compatible with Julia-1.0, so I built a compatible version with an older version of `BinaryBuilder` locally and uploaded on the Github releases of this repo.
* bugfixes and TODO list:
- [x] handle typedef anonymous structs/enums correctly using visr's method(close #208, fix #190)
- [x] integrate CEnums(cherrypick Simon's old PR close #162) 
- [x] refactor cindex directly on top of generated wrapper - [x] make wrap_c work again 
- [x] add tests 
- [x] use LLVMBuilder to provide an out-of-box installation experience:
  - fix #211, fix #197, fix #183, fix #65 
  - potentially fix #163 and #39 since with BB2 we install those headers in the same place on all platforms
  - close #172(obsolete), close #145(obsolete), close #142(looks like an installation problem), close #75(obsolete), close #49(obsolete)
- [x] handle opaque struct typealias appropriately(#84)  
- [x] "$" should be "\\$"(#196, #206)
- [x] CEnums doesn't like enums with minus field values
- [ ] sort include headers(have no idea about the effect of the following code:)
https://github.com/ihnorton/Clang.jl/blob/1c5f425dc4cdd469f0c66a3c667592edf42dd4e2/src/wrap_c.jl#L712-L716
- [x] build docs by Documenter.jl
- [x] update examples and README(#209)

### CODE REVIEW

**Comment by ihnorton** [comment]
I'll try to give this a read-through this weekend, very cool!

**Comment by Gnimuc** [comment]
the CI failure on Linux might due to the compatibility of the LLVM binaries. I've released two windows binaries and it works well on my VM.

**Comment by musm** [comment]
This is great, thanks for the hard work.

File: deps/build.jl [hunk 1]
```diff
@@ -3,90 +3,41 @@ using BinaryProvider # requires BinaryProvider 0.3.0 or later
...
-            error("no system llvm-config: $err")
-        end
-    end
-    LLVM_CONFIG = ENV["LLVM_CONFIG"]
-    llvm_libdir = readchomp(`$(LLVM_CONFIG) --libdir`)
-    if !ispath(llvm_libdir)
-        error("llvm-config returned non-existent libdir path: '$(llvm_libdir)")
-    end
+# Download binaries from hosted location
+bin_prefix = "https://github.com/ihnorton/Clang.jl/releases/download/Julia1.0-compatible"
```
Comment (vchuravy) [inline deps/build.jl]: Cool!  This looks like we actually want to have a "LLVMBuilder.jl" that has a hard-bound on the Julia version that you can depend on through the package-system, so that each version of Julia get's the right version of LLVMBuilder (and of course we should provide compatible releases (my apologies)). Also it means  we should become a bit more conservative in what LLVMBuilder provides and maybe have a second mode for the more experimental features.



cc @staticfloat

Comment (staticfloat) [reply deps/build.jl]: It saddens me that LLVM is so incompatible.

Let's create a `JuliaCompatibleLLVM` in [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil), register `JuliaCompatibleLLVM.jl`, hook up the appropriate `BinaryProvider` junk, and keep `JuliaCompatibleLLVM` as close to base Julia's `LLVM` as possible. We can keep `LLVMBuilder` with all the bells and whistles that others may want.

**Comment by ihnorton** [comment]
@Gnimuc I started taking a look through this. Wow! It is a lot of work and some really nice changes. Thank you!

**Comment by ihnorton** [comment]
To start off at a high level, this change immediately stood out out:

> module cindex's CL-prefixed types are removed, since methods are now directly dynamic-dispatched on Val{CEnum} value types(not sure whether this is a good idea or not).

Not sure either -- did you have considerations for performance that led in this direction? At first glance, it feels a little bit unwieldy for a high-level API (IIUC, have to pull out the enum, wrap in a `Val` etc. to pass a cursor to functions).

**Comment by Gnimuc** [comment]
It looks like this PR downgraded the package too much. 😅 For backward compatibility, it's also not a good idea to remove CL-prefixed types. But it seems very easy to get them back -- regenerate those types from the CX enums and define some conversion methods.

**Comment by Gnimuc** [comment]
@ihnorton I've brought those CL-types back and it's indeed much faster than dispatching on `Val`.

**Comment by Gnimuc** [comment]
gently bump. hi @ihnorton, is there any chance to get this PR merged before Julia-1.1 release? 

Since the LLVM & Clang used in Julia-1.1 are not compatible with those in used Julia-1.0, we need to cap this package to Julia-1.0 firstly, tag a v0.8 release and then provide Julia-1.1 support and tag a v0.9 release. Or should we just jump over Julia-1.0 and directly target Julia-1.1?

**Comment by ihnorton** [comment]
> cap this package to Julia-1.0 firstly, tag a v0.8 release and then provide Julia-1.1 support and tag a v0.9 release. Or should we just jump over Julia-1.0 and directly target Julia-1.1?

This sounds good! The compatibility of generated bindings is more important than what version Clang.jl will run on, so I think it is fine to target Julia 1.1.

**Comment by ihnorton** [comment]
@Gnimuc this looks great. I looked through the generated files in https://github.com/SCIP-Interfaces/SCIP.jl/pull/76 as the large test, and the output is very nice.

I'm not sure what is up with the rebase conflict, but please go ahead and tag then merge when you are ready 👍

**Comment by Gnimuc** [comment]
I also get rebase conflicts, so close this and submit a new PR.
