### ISSUE TITLE
failure to build on OS X (v0.0.0 and master)

### ISSUE THREAD

**Issue by StefanKarpinski** [ihnorton/Clang.jl#49]
``` julia
julia> Pkg.build("Clang")
INFO: Building Clang
g++ wrapclang.cpp -fPIC -c -o wrapclang.cpp.o -I"/Users/stefan/projects/julia//usr/include" -g -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fPIC
wrapclang.cpp:6:10: fatal error: 'clang-c/Index.h' file not found
#include "clang-c/Index.h"
         ^
1 error generated.
make: *** [wrapclang.cpp.o] Error 1
================================[ ERROR: Clang ]================================

failed process: Process(`make`, ProcessExited(2)) [2]
while loading /Users/stefan/.julia/Clang/deps/build.jl, in expression starting on line 6

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Clang had build errors.

 - packages with build errors remain installed in /Users/stefan/.julia
 - build a package and all its dependencies with `Pkg.build(pkg)`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

Not sure where to start debugging this.
